[project]
name = "multi-agent-llm"
description = "A multi-agent LLM system using OpenAI, Ollama, Gemini, Groq, LangChain, LangGraph, AutoGen, Gradio, and related frameworks"
version = "0.1.0"
requires-python = "==3.12.11"

[tool.uv.dependencies]
openai = "0.27.2"

